### ISSUE TITLE
Paper 1.8.8 / Paper 1.14.4 issues.

### ISSUE THREAD

**Issue by ryderbelserion** [illyria-io/SkyblockX#12]
/sbx calc on 1.8.8 paper caused this error to show up.

[SBX Calc Error](https://paste.illyria.io/view/9fabb9d12e5a235c2388564717d66dc1065f0f8d2e2d20893fd4d0d41a5d18ba)

/is member at first would not open because it said that it required PAPI but once that was added, It said unable to find an nms item clone for ItemStack

[NMS Item Clone Error](https://paste.illyria.io/view/027b609fdb4ba5d57dd09baff38f25181b1070326d2481095f081994e4b2e2b8)

The other error was when using /is promote, I promoted my alt "mitchy387" as leader then I went on mitchy387 and tried to promote Asruna as the island leader but was met with NPE's in the console, I disbanded the island and recreated and repeated the steps but met with the same issue and even deleted then reinstalled everything. 

[Promotion Error](https://paste.illyria.io/view/bc09ebec6cb7a6831aacba38f9fe464668dfdd4330727bba03c0d2232b11a0e4)

Afterwards as long as I didn't remove the island or restart, I couldn't do anything related to Asruna after the leadership switch, Kick, invite etc. ^ These above are on 1.8.8 paperspigot and the promotion error probably on any version.

Last thing I noticed when I decided to take a look on 1.14.4 is the island creation / deletion was weird, sometimes the borders wouldn't show up properly so I'd be unable to do anything as I am "outside" the border. 

It kept doing that for a few more islands after doing /is delete then teleported me back into the very first island I got from /is create. 

Other misc things I just did in a PR which is awaiting review

**Comment by prosavage** [comment]
I fixed the SBX Calc error by using reflection to find the 1.11.2 and lower compatible methods. 
https://github.com/illyria-io/SkyblockX/commit/db382e611c8af94ec85f541b5b5c20d1a0171e96

The NMS item clone error is caused by the API I use for GUIs. I went ahead and made it use PLAYER_HEAD instead of AIR. 
https://github.com/illyria-io/SkyblockX/commit/bd7c8882bec1479f65ae1442b1d6a2f48699682a

Please test these and make sure it works on your end, I will work on the last one tomorrow.

**Comment by prosavage** [comment]
Fixed the island promotion bug.
https://github.com/illyria-io/SkyblockX/commit/9157672673f08be3c6f3d7720dab42973a9511fd
