### ISSUE TITLE
Border protection bug

### ISSUE THREAD

**Issue by unsky559** [illyria-io/SkyblockX#30]
Actually, players can leave his island by just of toggle off the border visibility. Just watch how it is possible [Video](https://youtu.be/opujfnUTiIk)

**Comment by prosavage** [comment]
I can add a PlayerMoveEvent check or a timer based check to see if someone is on another person's island without teleporting.

I would need to basically do math to check if someone is in the gap between islands, and if the plugin is configured to have NO gap, well, then it would not work.

I try to avoid the PlayerMoveEvent however, because it is VERY intensive on the server, and a big focus of this Skyblock core is to be able to handle large servers. 

I think the easiest/best way is to actually have a way to disable turning off borders IMO. This would work universally, another way is to make the gap so large it cannot be crossed by jumping, however, fireworks + elytra are a thing in 1.9+, so it can be bypassed.

**Comment by prosavage** [comment]
I can add a PlayerMoveEvent but I would prefer if we can reach a more creative solution to fixing this.

**Comment by unsky559** [comment]
Try to see how it is realised in WorldGuard. It has a flag called `exit` that disallow exit players from region

**Comment by unsky559** [comment]
Is the `PlayerToggleFlightEvent`  called when player use elytra? If it does it can slove bypass by flying.

**Comment by prosavage** [comment]
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityToggleGlideEvent.html


It calls this event @unsky559

**Comment by prosavage** [comment]
There would be a logic maybe of 

The event fires when they land, and we check if they're not allowed to be on the island?

So we would allow it if

- Co-op 
- Allows visitors
- Is own island.

**Comment by prosavage** [comment]
@unsky559 take a look at the build in the pull request linked above and see if it does the trick for you
