### ISSUE TITLE
Remove Prefix of "/is top" bar

### ISSUE THREAD

**Issue by michaelsieminski** [illyria-io/SkyblockX#38]
is it possible that you remove the prefix from /is top header-bar? it looks a bit weird when there is a prefix not like [!]

**Comment by prosavage** [comment]
Yeah, so I mean I could, I have a global prefix that is configurable in the message file, so you can edit that.

I will remove it from the code, and others can just add it if they want.


You can get the latest builds, since theyre built automatically on my build server, on here: https://dl.savagelabs.net
