### ISSUE TITLE
Add Auto-Updater

### ISSUE THREAD

**Issue by michaelsieminski** [illyria-io/SkyblockX#45]
Hello, what do you think about adding an auto updater for the plugin so people don't have to download it all the time manually?

**Comment by prosavage** [comment]
I'm sure I can write something pretty simple actually, just to check if the current jar file is not the same as the latest one I guess.

**Comment by unsky559** [comment]
This can cause many errors on the production server. When I updated the plugin, I could not return to my island, since the point of the house was broken. Also, changes in the configuration files changed my config and some settings had to be reconfigured. Also, as I already wrote #43, after updating was the errors with island border and a lot of errors in the console.
